-- AlterTable
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "facebookPostId" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "reach" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "impressions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "engagements" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "clicks" INTEGER NOT NULL DEFAULT 0;
